version: '3.8'

services:
  app:
    build: .
    container_name: tunnel-ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./videos:/app/videos
      - ./tests/generated:/app/tests/generated
    depends_on:
      - redis
    networks:
      - test-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tunnel-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - test-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  test-network:
    driver: bridge